package com.nong.nongo2o.greenDaoGen;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.nong.nongo2o.entity.domain.City;
import com.nong.nongo2o.entity.bean.EaseUserInfo;

import com.nong.nongo2o.greenDaoGen.CityDao;
import com.nong.nongo2o.greenDaoGen.EaseUserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityDaoConfig;
    private final DaoConfig easeUserInfoDaoConfig;

    private final CityDao cityDao;
    private final EaseUserInfoDao easeUserInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityDaoConfig = daoConfigMap.get(CityDao.class).clone();
        cityDaoConfig.initIdentityScope(type);

        easeUserInfoDaoConfig = daoConfigMap.get(EaseUserInfoDao.class).clone();
        easeUserInfoDaoConfig.initIdentityScope(type);

        cityDao = new CityDao(cityDaoConfig, this);
        easeUserInfoDao = new EaseUserInfoDao(easeUserInfoDaoConfig, this);

        registerDao(City.class, cityDao);
        registerDao(EaseUserInfo.class, easeUserInfoDao);
    }
    
    public void clear() {
        cityDaoConfig.clearIdentityScope();
        easeUserInfoDaoConfig.clearIdentityScope();
    }

    public CityDao getCityDao() {
        return cityDao;
    }

    public EaseUserInfoDao getEaseUserInfoDao() {
        return easeUserInfoDao;
    }

}
